---
openapi: "3.1.0"
info:
  title: "Connections"
  version: "1.0.0"
  description: "Programatically control Airbyte Cloud, OSS & Enterprise."
servers:
  - url: "https://api.airbyte.com/v1"
    description: "Airbyte API v1"
paths:
  /connections:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConnectionCreateRequest"
            examples:
              Connection Creation Request Example:
                value:
                  sourceId: "95e66a59-8045-4307-9678-63bc3c9b8c93"
                  destinationId: "e478de0d-a3a0-475c-b019-25f7dd29e281"
                  name: "Postgres-to-Bigquery"
        required: true
      tags:
        - "public_connections"
        - "public"
        - "Connections"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConnectionResponse"
              examples:
                Connection Creation Response Example:
                  value:
                    connectionId: "9924bcd0-99be-453d-ba47-c2c9766f7da5"
          description: "Successful operation"
        "400":
          description: "Invalid data"
        "403":
          description: "Not allowed"
      operationId: "createConnection"
      x-speakeasy-alias: "createConnection"
      x-speakeasy-group: "Connections"
      summary: "Create a connection"
      x-speakeasy-entity-operation: "Connection#create"
    get:
      tags:
        - "public_connections"
        - "public"
        - "Connections"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConnectionsResponse"
          description: "Successful operation"
        "403":
          description: "Not allowed"
        "404":
          description: "Not found"
      operationId: "listConnections"
      x-speakeasy-alias: "listConnections"
      x-speakeasy-group: "Connections"
      summary: "List connections"
      x-speakeasy-entity-operation: "Connection#list"
      parameters:
        - name: "workspaceIds"
          description:
            "The UUIDs of the workspaces you wish to list connections for.\
            \ Empty list will retrieve all allowed workspaces."
          schema:
            type: "array"
            items:
              format: "uuid"
              type: "string"
          in: "query"
          required: false
        - name: "includeDeleted"
          description: "Include deleted connections in the returned results."
          schema:
            default: false
            type: "boolean"
          in: "query"
          required: false
        - name: "limit"
          description:
            "Set the limit on the number of Connections returned. The default\
            \ is 20."
          schema:
            format: "int32"
            type: "integer"
            minimum: 1
            maximum: 100
            default: 20
          in: "query"
        - name: "offset"
          description:
            "Set the offset to start at when returning Connections. The default\
            \ is 0"
          schema:
            type: "integer"
            format: "int32"
            minimum: 0
            default: 0
          in: "query"
  /connections/{connectionId}:
    get:
      tags:
        - "public_connections"
        - "public"
        - "Connections"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConnectionResponse"
              examples:
                Connection Get Response Example:
                  value:
                    workspaceId: "18dccc91-0ab1-4f72-9ed7-0b8fc27c5826"
                    name: "Postgres To Snowflake"
                    sourceId: "9924bcd0-99be-453d-ba47-c2c9766f7da5"
                    destinationId: "744cc0ed-7f05-4949-9e60-2a814f90c035"
          description: "Get a Connection by the id in the path."
        "403":
          description: "Not allowed"
        "404":
          description: "Not found"
      operationId: "getConnection"
      x-speakeasy-alias: "getConnection"
      x-speakeasy-group: "Connections"
      summary: "Get Connection details"
      x-speakeasy-entity-operation: "Connection#read"
    patch:
      tags:
        - "public_connections"
        - "public"
        - "Connections"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConnectionPatchRequest"
            examples:
              Connection Update Request Example:
                value:
                  sourceId: "95e66a59-8045-4307-9678-63bc3c9b8c93"
                  destinationId: "e478de0d-a3a0-475c-b019-25f7dd29e281"
                  name: "Postgres-to-Bigquery"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConnectionResponse"
              examples:
                Connection Get Response Example:
                  value:
                    workspaceId: "18dccc91-0ab1-4f72-9ed7-0b8fc27c5826"
                    name: "Postgres To Snowflake"
                    sourceId: "9924bcd0-99be-453d-ba47-c2c9766f7da5"
                    destinationId: "744cc0ed-7f05-4949-9e60-2a814f90c035"
          description: "Update a Connection by the id in the path."
        "403":
          description: "Not allowed"
        "404":
          description: "Not found"
      operationId: "patchConnection"
      x-speakeasy-alias: "patchConnection"
      x-speakeasy-group: "Connections"
      summary: "Update Connection details"
      x-speakeasy-entity-operation: "Connection#update"
    delete:
      tags:
        - "public_connections"
        - "public"
        - "Connections"
      responses:
        "204":
          description: "The resource was deleted successfully"
        "403":
          description: "Not allowed"
        "404":
          description: "Not found"
      operationId: "deleteConnection"
      x-speakeasy-alias: "deleteConnection"
      x-speakeasy-group: "Connections"
      summary: "Delete a Connection"
      x-speakeasy-entity-operation: "Connection#delete"
    parameters:
      - name: "connectionId"
        schema:
          format: "UUID"
          type: "string"
        in: "path"
        required: true
components:
  responses:
    InitiateOauthResponse:
      content:
        application/json: {}
      description:
        "Response from the initiate OAuth call should be an object with\
        \ a single property which will be the `redirect_url`. If a user is redirected\
        \ to this URL, they'll be prompted by the identity provider to authenticate."
      x-speakeasy-component: true
  schemas:
    WorkspaceId:
      type: "string"
      format: "uuid"
      x-speakeasy-component: true
    OrganizationId:
      type: "string"
      format: "uuid"
      x-speakeasy-component: true
    PermissionType:
      type: "string"
      description: "Describes what actions/endpoints the permission entitles to"
      enum:
        - "instance_admin"
        - "organization_admin"
        - "organization_editor"
        - "organization_reader"
        - "organization_member"
        - "workspace_owner"
        - "workspace_admin"
        - "workspace_editor"
        - "workspace_reader"
      x-speakeasy-component: true
    PublicPermissionType:
      type: "string"
      description:
        "Subset of `PermissionType` (removing `instance_admin`), could\
        \ be used in public-api."
      enum:
        - "organization_admin"
        - "organization_editor"
        - "organization_reader"
        - "organization_member"
        - "workspace_admin"
        - "workspace_editor"
        - "workspace_reader"
      x-speakeasy-component: true
    UserId:
      type: "string"
      description: "Internal Airbyte user ID"
      format: "uuid"
      x-speakeasy-component: true
    AuthProvider:
      type: "string"
      description: "Auth Provider"
      default: "airbyte"
      enum:
        - "airbyte"
        - "google_identity_platform"
        - "keycloak"
      x-speakeasy-component: true
    UserStatus:
      type: "string"
      description: "user status"
      enum:
        - "invited"
        - "registered"
        - "disabled"
      x-speakeasy-param-suppress-computed-diff: true
      x-speakeasy-component: true
    SelectedFieldInfo:
      type: "object"
      description:
        "Path to a field/column/property in a stream to be selected. For\
        \ example, if the field to be selected is a database column called \"foo\"\
        , this will be [\"foo\"]. Use multiple path elements for nested schemas."
      properties:
        fieldPath:
          type: "array"
          items:
            type: "string"
      x-speakeasy-component: true
    SelectedFields:
      description: "Paths to the fields that will be included in the configured catalog."
      type: "array"
      items:
        $ref: "#/components/schemas/SelectedFieldInfo"
      x-speakeasy-component: true
    OAuthConfiguration:
      description:
        "The values required to configure OAuth flows. The schema for this\
        \ must match the `OAuthConfigSpecification.oauthUserInputFromConnectorConfigSpecification`\
        \ schema."
      x-speakeasy-component: true
    OAuthInputConfiguration:
      $ref: "#/components/schemas/OAuthConfiguration"
      x-speakeasy-component: true
    ApplicationCreate:
      required:
        - "name"
      type: "object"
      properties:
        name:
          type: "string"
      x-speakeasy-component: true
    ApplicationReadList:
      required:
        - "applications"
      type: "object"
      properties:
        applications:
          type: "array"
          items:
            $ref: "#/components/schemas/ApplicationRead"
      x-speakeasy-component: true
    ApplicationRead:
      required:
        - "id"
        - "name"
        - "clientId"
        - "clientSecret"
        - "createdAt"
      type: "object"
      properties:
        id:
          type: "string"
        name:
          type: "string"
        clientId:
          type: "string"
        clientSecret:
          type: "string"
        createdAt:
          type: "integer"
          format: "int64"
      x-speakeasy-component: true
    ApplicationTokenRequestWithGrant:
      required:
        - "client_id"
        - "client_secret"
        - "grant_type"
      type: "object"
      properties:
        client_id:
          type: "string"
        client_secret:
          type: "string"
        grant-type:
          enum:
            - "client_credentials"
      x-speakeasy-component: true
    PublicAccessTokenResponse:
      required:
        - "access_token"
        - "token_type"
        - "expires_in"
      type: "object"
      properties:
        access_token:
          type: "string"
        token_type:
          enum:
            - "Bearer"
        expires_in:
          type: "integer"
          format: "int64"
      x-speakeasy-component: true
    RedirectUrlResponse:
      title: "Root Type for RedirectUrlResponse"
      description: ""
      type: "object"
      properties:
        redirectUrl:
          format: "url"
          type: "string"
      example:
        redirectUrl: "https://example.com"
      x-speakeasy-component: true
    JobResponse:
      title: "Root Type for JobResponse"
      description: "Provides details of a single job."
      required:
        - "jobId"
        - "status"
        - "jobType"
        - "startTime"
        - "connectionId"
      type: "object"
      properties:
        jobId:
          format: "int64"
          type: "integer"
        status:
          $ref: "#/components/schemas/JobStatusEnum"
        jobType:
          $ref: "#/components/schemas/JobTypeEnum"
        startTime:
          type: "string"
        connectionId:
          format: "UUID"
          type: "string"
        lastUpdatedAt:
          type: "string"
        duration:
          description: "Duration of a sync in ISO_8601 format"
          type: "string"
        bytesSynced:
          format: "int64"
          type: "integer"
        rowsSynced:
          format: "int64"
          type: "integer"
      example:
        id: "18dccc91-0ab1-4f72-9ed7-0b8fc27c5826"
        status: "running"
        jobType: "sync"
        startTime: "2023-03-25T01:30:50Z"
        duration: "PT8H6M12S"
      x-speakeasy-component: true
    JobsResponse:
      title: "Root Type for JobsResponse"
      description: ""
      required:
        - "data"
      type: "object"
      properties:
        previous:
          type: "string"
        next:
          type: "string"
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/JobResponse"
      example:
        next: "https://api.airbyte.com/v1/jobs?limit=5&offset=10"
        previous: "https://api.airbyte.com/v1/jobs?limit=5&offset=0"
        data:
          - id: "18dccc91-0ab1-4f72-9ed7-0b8fc27c5826"
            status: "running"
            jobType: "sync"
            startTime: "2023-03-25T01:30:50Z"
      x-speakeasy-component: true
    ConnectionCreateRequest:
      required:
        - "sourceId"
        - "destinationId"
      type: "object"
      properties:
        name:
          description: "Optional name of the connection"
          type: "string"
        sourceId:
          format: "uuid"
          type: "string"
        destinationId:
          format: "uuid"
          type: "string"
        configurations:
          $ref: "#/components/schemas/StreamConfigurations"
        schedule:
          $ref: "#/components/schemas/AirbyteApiConnectionSchedule"
        dataResidency:
          $ref: "#/components/schemas/GeographyEnum"
        namespaceDefinition:
          $ref: "#/components/schemas/NamespaceDefinitionEnum"
        namespaceFormat:
          type: "string"
          description:
            "Used when namespaceDefinition is 'custom_format'. If blank\
            \ then behaves like namespaceDefinition = 'destination'. If \"${SOURCE_NAMESPACE}\"\
            \ then behaves like namespaceDefinition = 'source'."
          default: null
          example: "${SOURCE_NAMESPACE}"
        prefix:
          type: "string"
          description:
            "Prefix that will be prepended to the name of each stream when\
            \ it is written to the destination (ex. “airbyte_” causes “projects” =>\
            \ “airbyte_projects”)."
        nonBreakingSchemaUpdatesBehavior:
          $ref: "#/components/schemas/NonBreakingSchemaUpdatesBehaviorEnum"
        status:
          $ref: "#/components/schemas/ConnectionStatusEnum"
      x-speakeasy-entity: "Connection"
      x-speakeasy-param-suppress-computed-diff: true
      x-speakeasy-component: true
    ConnectionPatchRequest:
      type: "object"
      properties:
        name:
          description: "Optional name of the connection"
          type: "string"
        configurations:
          $ref: "#/components/schemas/StreamConfigurations"
        schedule:
          $ref: "#/components/schemas/AirbyteApiConnectionSchedule"
        dataResidency:
          $ref: "#/components/schemas/GeographyEnumNoDefault"
        namespaceDefinition:
          $ref: "#/components/schemas/NamespaceDefinitionEnumNoDefault"
        namespaceFormat:
          type: "string"
          description:
            "Used when namespaceDefinition is 'custom_format'. If blank\
            \ then behaves like namespaceDefinition = 'destination'. If \"${SOURCE_NAMESPACE}\"\
            \ then behaves like namespaceDefinition = 'source'."
          default: null
          example: "${SOURCE_NAMESPACE}"
        prefix:
          type: "string"
          description:
            "Prefix that will be prepended to the name of each stream when\
            \ it is written to the destination (ex. “airbyte_” causes “projects” =>\
            \ “airbyte_projects”)."
        nonBreakingSchemaUpdatesBehavior:
          $ref: "#/components/schemas/NonBreakingSchemaUpdatesBehaviorEnumNoDefault"
        status:
          $ref: "#/components/schemas/ConnectionStatusEnum"
      x-speakeasy-entity: "Connection"
      x-speakeasy-param-suppress-computed-diff: true
      x-speakeasy-component: true
    JobCreateRequest:
      title: "Root Type for JobCreate"
      description:
        "Creates a new Job from the configuration provided in the request\
        \ body."
      required:
        - "jobType"
        - "connectionId"
      type: "object"
      properties:
        connectionId:
          format: "UUID"
          type: "string"
        jobType:
          $ref: "#/components/schemas/JobTypeEnum"
      example:
        connectionId: "18dccc91-0ab1-4f72-9ed7-0b8fc27c5826"
        jobType: "sync"
      x-speakeasy-component: true
    JobStatusEnum:
      enum:
        - "pending"
        - "running"
        - "incomplete"
        - "failed"
        - "succeeded"
        - "cancelled"
      type: "string"
      x-speakeasy-component: true
    JobTypeEnum:
      description:
        "Enum that describes the different types of jobs that the platform\
        \ runs."
      enum:
        - "sync"
        - "reset"
        - "refresh"
        - "clear"
      type: "string"
      x-speakeasy-component: true
    SourceCreateRequest:
      required:
        - "name"
        - "workspaceId"
        - "configuration"
      type: "object"
      properties:
        name:
          description: "Name of the source e.g. dev-mysql-instance."
          type: "string"
        definitionId:
          description:
            "The UUID of the connector definition. One of configuration.sourceType\
            \ or definitionId must be provided."
          format: "uuid"
          type: "string"
        workspaceId:
          format: "uuid"
          type: "string"
        configuration:
          $ref: "#/components/schemas/SourceConfiguration"
        secretId:
          description: "Optional secretID obtained through the  OAuth redirect flow."
          type: "string"
      x-implements: "io.airbyte.api.common.ConfigurableActor"
      x-speakeasy-entity: "Source"
      x-speakeasy-param-suppress-computed-diff: true
      x-speakeasy-component: true
    SourcePutRequest:
      required:
        - "name"
        - "configuration"
      type: "object"
      properties:
        name:
          type: "string"
        configuration:
          $ref: "#/components/schemas/SourceConfiguration"
      x-implements: "io.airbyte.api.common.ConfigurableActor"
      x-speakeasy-entity: "Source"
      x-speakeasy-param-suppress-computed-diff: true
      x-speakeasy-component: true
    SourcePatchRequest:
      type: "object"
      properties:
        name:
          type: "string"
          example: "My source"
        workspaceId:
          format: "uuid"
          type: "string"
        configuration:
          $ref: "#/components/schemas/SourceConfiguration"
        secretId:
          description: "Optional secretID obtained through the  OAuth redirect flow."
          type: "string"
      x-implements: "io.airbyte.api.common.ConfigurableActor"
      x-speakeasy-entity: "Source"
      x-speakeasy-param-suppress-computed-diff: true
      x-speakeasy-component: true
    ConnectionResponse:
      title: "Root Type for ConnectionResponse"
      description: "Provides details of a single connection."
      type: "object"
      required:
        - "connectionId"
        - "name"
        - "sourceId"
        - "destinationId"
        - "workspaceId"
        - "status"
        - "schedule"
        - "dataResidency"
        - "configurations"
      properties:
        connectionId:
          format: "UUID"
          type: "string"
        name:
          type: "string"
        sourceId:
          format: "UUID"
          type: "string"
        destinationId:
          format: "UUID"
          type: "string"
        workspaceId:
          format: "UUID"
          type: "string"
        status:
          $ref: "#/components/schemas/ConnectionStatusEnum"
        schedule:
          $ref: "#/components/schemas/ConnectionScheduleResponse"
        dataResidency:
          $ref: "#/components/schemas/GeographyEnum"
        nonBreakingSchemaUpdatesBehavior:
          $ref: "#/components/schemas/NonBreakingSchemaUpdatesBehaviorEnum"
        namespaceDefinition:
          $ref: "#/components/schemas/NamespaceDefinitionEnum"
        namespaceFormat:
          type: "string"
        prefix:
          type: "string"
        configurations:
          $ref: "#/components/schemas/StreamConfigurations"
      x-speakeasy-entity: "Connection"
      x-speakeasy-param-suppress-computed-diff: true
      x-speakeasy-component: true
    AirbyteApiConnectionSchedule:
      description:
        "schedule for when the the connection should run, per the schedule\
        \ type"
      type: "object"
      required:
        - "scheduleType"
      properties:
        scheduleType:
          $ref: "#/components/schemas/ScheduleTypeEnum"
        cronExpression:
          type: "string"
      x-speakeasy-component: true
    ScheduleTypeEnum:
      type: "string"
      enum:
        - "manual"
        - "cron"
      x-speakeasy-component: true
    ConnectionScheduleResponse:
      description:
        "schedule for when the the connection should run, per the schedule\
        \ type"
      type: "object"
      required:
        - "scheduleType"
      properties:
        scheduleType:
          $ref: "#/components/schemas/ScheduleTypeWithBasicEnum"
        cronExpression:
          type: "string"
        basicTiming:
          type: "string"
      x-speakeasy-component: true
    ScheduleTypeWithBasicEnum:
      type: "string"
      enum:
        - "manual"
        - "cron"
        - "basic"
      x-speakeasy-component: true
    GeographyEnum:
      type: "string"
      enum:
        - "auto"
        - "us"
        - "eu"
      default: "auto"
      x-speakeasy-component: true
    GeographyEnumNoDefault:
      type: "string"
      enum:
        - "auto"
        - "us"
        - "eu"
      x-speakeasy-component: true
    ConnectionStatusEnum:
      type: "string"
      enum:
        - "active"
        - "inactive"
        - "deprecated"
      x-speakeasy-component: true
    NamespaceDefinitionEnum:
      type: "string"
      description: "Define the location where the data will be stored in the destination"
      enum:
        - "source"
        - "destination"
        - "custom_format"
      default: "destination"
      x-speakeasy-component: true
    NonBreakingSchemaUpdatesBehaviorEnum:
      type: "string"
      description:
        "Set how Airbyte handles syncs when it detects a non-breaking schema\
        \ change in the source"
      enum:
        - "ignore"
        - "disable_connection"
        - "propagate_columns"
        - "propagate_fully"
      default: "ignore"
      x-speakeasy-component: true
    NamespaceDefinitionEnumNoDefault:
      type: "string"
      description: "Define the location where the data will be stored in the destination"
      enum:
        - "source"
        - "destination"
        - "custom_format"
      x-speakeasy-component: true
    NonBreakingSchemaUpdatesBehaviorEnumNoDefault:
      type: "string"
      description:
        "Set how Airbyte handles syncs when it detects a non-breaking schema\
        \ change in the source"
      enum:
        - "ignore"
        - "disable_connection"
        - "propagate_columns"
        - "propagate_fully"
      x-speakeasy-component: true
    DestinationResponse:
      title: "Root Type for DestinationResponse"
      description: "Provides details of a single destination."
      type: "object"
      required:
        - "destinationId"
        - "name"
        - "destinationType"
        - "workspaceId"
        - "configuration"
      properties:
        destinationId:
          format: "UUID"
          type: "string"
        name:
          type: "string"
        destinationType:
          type: "string"
        workspaceId:
          format: "UUID"
          type: "string"
        configuration:
          $ref: "#/components/schemas/DestinationConfiguration"
      example:
        destinationId: "18dccc91-0ab1-4f72-9ed7-0b8fc27c5826"
        name: "Analytics Team Postgres"
        destinationType: "postgres"
        workspaceId: "871d9b60-11d1-44cb-8c92-c246d53bf87e"
      x-speakeasy-component: true
    SourceResponse:
      title: "Root Type for SourceResponse"
      description: "Provides details of a single source."
      type: "object"
      required:
        - "sourceId"
        - "name"
        - "sourceType"
        - "workspaceId"
        - "configuration"
      properties:
        sourceId:
          format: "UUID"
          type: "string"
        name:
          type: "string"
        sourceType:
          type: "string"
        workspaceId:
          format: "UUID"
          type: "string"
        configuration:
          $ref: "#/components/schemas/SourceConfiguration"
      example:
        sourceId: "18dccc91-0ab1-4f72-9ed7-0b8fc27c5826"
        name: "Analytics Team Postgres"
        sourceType: "postgres"
        workspaceId: "871d9b60-11d1-44cb-8c92-c246d53bf87e"
      x-speakeasy-component: true
    DestinationCreateRequest:
      required:
        - "name"
        - "workspaceId"
        - "configuration"
      type: "object"
      properties:
        name:
          description: "Name of the destination e.g. dev-mysql-instance."
          type: "string"
        definitionId:
          description:
            "The UUID of the connector definition. One of configuration.destinationType\
            \ or definitionId must be provided."
          format: "uuid"
          type: "string"
        workspaceId:
          format: "uuid"
          type: "string"
        configuration:
          $ref: "#/components/schemas/DestinationConfiguration"
      x-implements: "io.airbyte.api.common.ConfigurableActor"
      x-speakeasy-entity: "Destination"
      x-speakeasy-param-suppress-computed-diff: true
      x-speakeasy-component: true
    DestinationPatchRequest:
      type: "object"
      properties:
        name:
          type: "string"
        configuration:
          $ref: "#/components/schemas/DestinationConfiguration"
      x-implements: "io.airbyte.api.common.ConfigurableActor"
      x-speakeasy-entity: "Destination"
      x-speakeasy-param-suppress-computed-diff: true
      x-speakeasy-component: true
    DestinationPutRequest:
      required:
        - "name"
        - "configuration"
      type: "object"
      properties:
        name:
          type: "string"
        configuration:
          $ref: "#/components/schemas/DestinationConfiguration"
      x-implements: "io.airbyte.api.common.ConfigurableActor"
      x-speakeasy-entity: "Destination"
      x-speakeasy-param-suppress-computed-diff: true
      x-speakeasy-component: true
    WorkspaceCreateRequest:
      required:
        - "name"
      type: "object"
      properties:
        name:
          description: "Name of the workspace"
          type: "string"
        organizationId:
          description: "ID of organization to add workspace to."
          format: "uuid"
          type: "string"
      x-speakeasy-entity: "Workspace"
      x-speakeasy-param-suppress-computed-diff: true
      x-speakeasy-component: true
    WorkspaceUpdateRequest:
      required:
        - "name"
      type: "object"
      properties:
        name:
          description: "Name of the workspace"
          type: "string"
      x-speakeasy-entity: "Workspace"
      x-speakeasy-param-suppress-computed-diff: true
      x-speakeasy-component: true
    WorkspaceResponse:
      title: "Root Type for WorkspaceResponse"
      description: "Provides details of a single workspace."
      type: "object"
      required:
        - "workspaceId"
        - "name"
        - "dataResidency"
      properties:
        workspaceId:
          format: "UUID"
          type: "string"
        name:
          type: "string"
        dataResidency:
          $ref: "#/components/schemas/GeographyEnum"
      x-speakeasy-entity: "Workspace"
      x-speakeasy-param-suppress-computed-diff: true
      x-speakeasy-component: true
    UserResponse:
      title: "Root Type for UserResponse"
      description: "Provides details of a single user in an organization."
      type: "object"
      required:
        - "id"
        - "name"
        - "email"
      properties:
        name:
          description: "Name of the user"
          type: "string"
        id:
          $ref: "#/components/schemas/UserId"
        email:
          type: "string"
          format: "email"
      x-speakeasy-entity: "User"
      x-speakeasy-param-suppress-computed-diff: true
      x-speakeasy-component: true
    UsersResponse:
      title: "Root Type for UsersResponse"
      description: "List/Array of multiple users in an organization"
      required:
        - "data"
      type: "object"
      properties:
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/UserResponse"
      x-speakeasy-component: true
      x-speakeasy-entity: "User"
      x-speakeasy-param-suppress-computed-diff: true
    PermissionCreateRequest:
      required:
        - "permissionType"
        - "userId"
      type: "object"
      properties:
        permissionType:
          $ref: "#/components/schemas/PublicPermissionType"
        userId:
          $ref: "#/components/schemas/UserId"
        workspaceId:
          $ref: "#/components/schemas/WorkspaceId"
        organizationId:
          $ref: "#/components/schemas/OrganizationId"
      x-speakeasy-entity: "Permission"
      x-speakeasy-param-suppress-computed-diff: true
      x-speakeasy-component: true
    PermissionUpdateRequest:
      required:
        - "permissionType"
      type: "object"
      properties:
        permissionType:
          $ref: "#/components/schemas/PermissionType"
      x-speakeasy-entity: "Permission"
      x-speakeasy-param-suppress-computed-diff: true
      x-speakeasy-component: true
    PermissionResponse:
      title: "Root Type for PermissionResponse"
      description: "Provides details of a single permission."
      type: "object"
      required:
        - "permissionId"
        - "permissionType"
        - "userId"
      properties:
        permissionId:
          type: "string"
          format: "uuid"
        permissionType:
          $ref: "#/components/schemas/PermissionType"
        userId:
          $ref: "#/components/schemas/UserId"
        workspaceId:
          $ref: "#/components/schemas/WorkspaceId"
        organizationId:
          $ref: "#/components/schemas/OrganizationId"
      x-speakeasy-entity: "Permission"
      x-speakeasy-param-suppress-computed-diff: true
      x-speakeasy-component: true
    PermissionScope:
      description: "Scope of a single permission, e.g. workspace, organization"
      type: "string"
      enum:
        - "workspace"
        - "organization"
        - "none"
      x-speakeasy-component: true
    PermissionResponseRead:
      title: "Root type for PermissionResponseRead"
      description: "Reformat PermissionResponse with permission scope"
      type: "object"
      required:
        - "permissionId"
        - "permissionType"
        - "userId"
        - "scope"
        - "scopeId"
      properties:
        permissionId:
          type: "string"
          format: "uuid"
        permissionType:
          $ref: "#/components/schemas/PermissionType"
        userId:
          $ref: "#/components/schemas/UserId"
        scopeId:
          type: "string"
          format: "uuid"
        scope:
          $ref: "#/components/schemas/PermissionScope"
      x-speakeasy-entity: "Permission"
      x-speakeasy-param-suppress-computed-diff: true
      x-speakeasy-component: true
    PermissionsResponse:
      title: "Root Type for PermissionsResponse"
      description: "List/Array of multiple permissions"
      required:
        - "data"
      type: "object"
      properties:
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/PermissionResponseRead"
      x-speakeasy-component: true
    OrganizationResponse:
      title: "Root Type for OrganizationResponse"
      description: "Provides details of a single organization for a user."
      type: "object"
      required:
        - "organizationId"
        - "organizationName"
        - "email"
      properties:
        organizationId:
          $ref: "#/components/schemas/OrganizationId"
        organizationName:
          type: "string"
        email:
          type: "string"
          format: "email"
      x-speakeasy-param-suppress-computed-diff: true
      x-speakeasy-component: true
    OrganizationsResponse:
      title: "Root Type for OrganizationsResponse"
      description: "List/Array of multiple organizations."
      required:
        - "data"
      type: "object"
      properties:
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/OrganizationResponse"
      x-speakeasy-component: true
    ConnectionsResponse:
      title: "Root Type for ConnectionsResponse"
      description: ""
      required:
        - "data"
      type: "object"
      properties:
        previous:
          type: "string"
        next:
          type: "string"
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/ConnectionResponse"
          default: []
      example:
        next: "https://api.airbyte.com/v1/connections?limit=5&offset=10"
        previous: "https://api.airbyte.com/v1/connections?limit=5&offset=0"
        data:
          - name: "test-connection"
          - connection_id: "18dccc91-0ab1-4f72-9ed7-0b8fc27c5826"
          - sourceId: "49237019-645d-47d4-b45b-5eddf97775ce"
          - destinationId: "al312fs-0ab1-4f72-9ed7-0b8fc27c5826"
          - schedule:
              scheduleType: "manual"
          - status: "active"
          - dataResidency: "auto"
      x-speakeasy-component: true
    SourcesResponse:
      title: "Root Type for SourcesResponse"
      description: ""
      required:
        - "data"
      type: "object"
      properties:
        previous:
          type: "string"
        next:
          type: "string"
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/SourceResponse"
      example:
        next: "https://api.airbyte.com/v1/sources?limit=5&offset=10"
        previous: "https://api.airbyte.com/v1/sources?limit=5&offset=0"
        data:
          sourceId: "18dccc91-0ab1-4f72-9ed7-0b8fc27c5826"
          name: "Analytics Team Postgres"
          sourceType: "postgres"
          workspaceId: "871d9b60-11d1-44cb-8c92-c246d53bf87e"
      x-speakeasy-component: true
    DestinationsResponse:
      title: "Root Type for DestinationsResponse"
      description: ""
      required:
        - "data"
      type: "object"
      properties:
        previous:
          type: "string"
        next:
          type: "string"
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/DestinationResponse"
      example:
        next: "https://api.airbyte.com/v1/destinations?limit=5&offset=10"
        previous: "https://api.airbyte.com/v1/destinations?limit=5&offset=0"
        data:
          destinationId: "18dccc91-0ab1-4f72-9ed7-0b8fc27c5826"
          name: "Analytics Team Postgres"
          destinationType: "postgres"
          workspaceId: "871d9b60-11d1-44cb-8c92-c246d53bf87e"
      x-speakeasy-component: true
    WorkspacesResponse:
      title: "Root Type for WorkspacesResponse"
      description: ""
      required:
        - "data"
      type: "object"
      properties:
        previous:
          type: "string"
        next:
          type: "string"
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/WorkspaceResponse"
      example:
        next: "https://api.airbyte.com/v1/workspaces?limit=5&offset=10"
        previous: "https://api.airbyte.com/v1/workspaces?limit=5&offset=0"
        data:
          workspaceId: "18dccc91-0ab1-4f72-9ed7-0b8fc27c5826"
          name: "Acme Company"
          dataResidency: "auto"
      x-speakeasy-component: true
    StreamConfiguration:
      description: "Configurations for a single stream."
      type: "object"
      required:
        - "name"
      properties:
        name:
          type: "string"
        syncMode:
          $ref: "#/components/schemas/ConnectionSyncModeEnum"
        cursorField:
          description:
            "Path to the field that will be used to determine if a record\
            \ is new or modified since the last sync. This field is REQUIRED if `sync_mode`\
            \ is `incremental` unless there is a default."
          type: "array"
          items:
            type: "string"
        primaryKey:
          description:
            "Paths to the fields that will be used as primary key. This\
            \ field is REQUIRED if `destination_sync_mode` is `*_dedup` unless it\
            \ is already supplied by the source schema."
          type: "array"
          items:
            type: "array"
            items:
              type: "string"
        selectedFields:
          description:
            "By default (if not provided in the request) all fields will\
            \ be synced. Otherwise, only the fields in this list will be synced."
          $ref: "#/components/schemas/SelectedFields"
      x-speakeasy-component: true
    StreamConfigurations:
      description: "A list of configured stream options for a connection."
      type: "object"
      properties:
        streams:
          type: "array"
          items:
            $ref: "#/components/schemas/StreamConfiguration"
      x-speakeasy-component: true
    StreamPropertiesResponse:
      description: "A list of stream properties."
      type: "array"
      items:
        $ref: "#/components/schemas/StreamProperties"
      x-speakeasy-component: true
    StreamProperties:
      description: "The stream properties associated with a connection."
      type: "object"
      properties:
        streamName:
          type: "string"
        syncModes:
          type: "array"
          items:
            $ref: "#/components/schemas/ConnectionSyncModeEnum"
        defaultCursorField:
          type: "array"
          items:
            type: "string"
        sourceDefinedCursorField:
          type: "boolean"
        sourceDefinedPrimaryKey:
          type: "array"
          items:
            type: "array"
            items:
              type: "string"
        propertyFields:
          type: "array"
          items:
            type: "array"
            items:
              type: "string"
      x-speakeasy-component: true
    ConnectionSyncModeEnum:
      enum:
        - "full_refresh_overwrite"
        - "full_refresh_append"
        - "incremental_append"
        - "incremental_deduped_history"
      x-speakeasy-component: true
    ActorTypeEnum:
      description: "Whether you're setting this override for a source or destination"
      enum:
        - "source"
        - "destination"
      x-speakeasy-component: true
    SourceConfiguration:
      description: The values required to configure the source.
      example: { user: "charles" }
    DestinationConfiguration:
      description: The values required to configure the destination.
      example: { user: "charles" }
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
